/**
 * SnowGeneratorExperimentation.hpp - Contains the class which renders the snow generation experiments.
 *
 * @author Mars Semenova
 * @date April 13, 2026
 */

#ifndef SNOWGENERATOREXPERIMENTATION_HPP
#define SNOWGENERATOREXPERIMENTATION_HPP

#include "SnowConstants.hpp"
#include "SnowGenerator.hpp"

// experiments enum
const GLuint DEG_OF_ALLOWANCE_EXP = 1;
const GLuint OPACITY_EXP = 2;
const GLuint OPACITY_VARIANCE_EXP = 3;
const GLuint NUM_LAYERS_EXP = 4;

// other vars
const GLfloat WET_SNOW_TEMP = 10;
const GLfloat DRY_SNOW_TEMP = -10;

class SnowGeneratorExperimentation {
private:
	// params
	GLfloat temp; // C
	SnowGeneratorData data;
	GLuint whichExp;

	// render params
	GLuint programID;

	GLuint MVPID;
	GLuint MID;
	GLuint VID;
	GLuint LightPosID;
	GLuint alphaID;

	GLuint vertexArrayID;
	GLuint vertBuffer;
	GLuint normalBuffer;
	GLuint colorBuffer;

	/**
	 * Helper method to get a wet snow particle generated by the Moeslund algorithm.
	 * @return SnowGeneratorData object with the particle info.
	 */
	SnowGeneratorData getMoeslundWet() {
		SnowGenerator snowGeneratorWet = SnowGenerator(WET_SNOW_TEMP);
		return snowGeneratorWet.generateSnowOnceMoeslund();
	}

	/**
	 * Helper method to get a dry snow particle generated by the Moeslund algorithm.
	 * @return SnowGeneratorData object with the particle info.
	 */
	SnowGeneratorData getMoeslundDry() {
		SnowGenerator snowGeneratorDry = SnowGenerator(DRY_SNOW_TEMP);
		return snowGeneratorDry.generateSnowOnceMoeslund();
	}

	/**
	 * Experiment for determining the optimal degree of allowance for theta and phi.
	 * @return Data to render.
	 */
	SnowGeneratorData degOfAllowanceExperiment() {
		SnowGeneratorData data;
		SnowGeneratorData dataReturned[8];
		GLuint numEntries = 0;
		GLfloat xPos[8], yPos[8], zPos[8];

		// moeslund wet
		dataReturned[0] = getMoeslundWet();
		xPos[0] = -10, yPos[0] = 2, zPos[0] = 0;

		SnowGenerator snowGeneratorWet = SnowGenerator(WET_SNOW_TEMP);
		// theta = 70, phi = 35, wet
		dataReturned[1] = snowGeneratorWet.generateSnowOnceExperimental(deg2rad(70), deg2rad(35), OPACITY_COEFF_MOESLUND, EPS_OPACITY_MOESLUND, NUM_LAYERS_WET_MOESLUND);
		xPos[1] = -3, yPos[1] = 2, zPos[1] = 0;

		// theta = 60, phi = 30, wet
		dataReturned[2] = snowGeneratorWet.generateSnowOnceExperimental(deg2rad(60), deg2rad(30), OPACITY_COEFF_MOESLUND, EPS_OPACITY_MOESLUND, NUM_LAYERS_WET_MOESLUND);
		xPos[2] = 3, yPos[2] = 2, zPos[2] = 0;

		// theta = 50, phi = 25, wet
		dataReturned[3] = snowGeneratorWet.generateSnowOnceExperimental(deg2rad(50), deg2rad(25), OPACITY_COEFF_MOESLUND, EPS_OPACITY_MOESLUND, NUM_LAYERS_WET_MOESLUND);
		xPos[3] = 10, yPos[3] = 2, zPos[3] = 0;

		SnowGenerator snowGeneratorDry = SnowGenerator(DRY_SNOW_TEMP);
		// moeslund dry
		dataReturned[4] = getMoeslundDry();
		xPos[4] = -4, yPos[4] = -2, zPos[4] = 0;

		// theta = 70, phi = 35, dry
		dataReturned[5] = snowGeneratorDry.generateSnowOnceExperimental(deg2rad(70), deg2rad(45), OPACITY_COEFF_MOESLUND, EPS_OPACITY_MOESLUND, NUM_LAYERS_DRY_MOESLUND);
		xPos[5] = -2, yPos[5] = -2, zPos[5] = 0;

		// theta = 60, phi = 30, dry
		dataReturned[6] = snowGeneratorDry.generateSnowOnceExperimental(deg2rad(60), deg2rad(30), OPACITY_COEFF_MOESLUND, EPS_OPACITY_MOESLUND, NUM_LAYERS_DRY_MOESLUND);
		xPos[6] = 2, yPos[6] = -2, zPos[6] = 0;

		// theta = 50, phi = 25, dry
		dataReturned[7] = snowGeneratorDry.generateSnowOnceExperimental(deg2rad(50), deg2rad(25), OPACITY_COEFF_MOESLUND, EPS_OPACITY_MOESLUND, NUM_LAYERS_DRY_MOESLUND);
		xPos[7] = 4, yPos[7] = -2, zPos[7] = 0;

		// update pos
		for (int x = 0; x < 8; x++) {
			numEntries += dataReturned[x].numPolys;
			for (int i = 0; i < dataReturned[x].numPolys*9; i+=3) {
				dataReturned[x].verts[i] += xPos[x];
				dataReturned[x].verts[i+1] += yPos[x];
				dataReturned[x].verts[i+2] += zPos[x];
			}
		}

		// merge + ret
		data.numPolys = numEntries;
		data.verts = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.normals = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.colours = (GLfloat*) malloc(numEntries*12*sizeof(GLfloat));
		GLuint offset = 0;
		for (int x = 0; x < 8; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*9; i++) {
				data.verts[i + offset] = dataReturned[x].verts[i];
				data.normals[i + offset] = dataReturned[x].normals[i];

			}
			offset += dataReturned[x].numPolys*9;
		}
		offset = 0;
		for (int x = 0; x < 8; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*12; i++) {
				data.colours[i + offset] = dataReturned[x].colours[i];
			}
			offset += dataReturned[x].numPolys*12;
		}

		return data;
	}

	/**
	 * Experiment for determining the optimal opacity coefficient to be used with the density to determine opacity of the triangles.
	 * @return Data to render.
	 */
	SnowGeneratorData opacityExperiment() {
		SnowGeneratorData data;
		SnowGeneratorData dataReturned[4];
		GLuint numEntries = 0;
		GLfloat xPos[4], yPos[4], zPos[4];

		// moeslund wet
		dataReturned[0] = getMoeslundWet();
		xPos[0] = -5, yPos[0] = 3, zPos[0] = 0;

		// moeslund dry
		dataReturned[1] = getMoeslundDry();
		xPos[1] = 3, yPos[1] = 3, zPos[1] = 0;

		// modded wet
		SnowGenerator snowGeneratorWet = SnowGenerator(WET_SNOW_TEMP);
		dataReturned[2] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, EPS_OPACITY_MOESLUND, NUM_LAYERS_WET_MOESLUND);
		xPos[2] = -5, yPos[2] = -3, zPos[2] = 0;

		// modded dry
		SnowGenerator snowGeneratorDry = SnowGenerator(DRY_SNOW_TEMP);
		dataReturned[3] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, EPS_OPACITY_MOESLUND, NUM_LAYERS_DRY_MOESLUND);
		xPos[3] = 3, yPos[3] = -3, zPos[3] = 0;

		// update pos
		for (int x = 0; x < 4; x++) {
			numEntries += dataReturned[x].numPolys;
			for (int i = 0; i < dataReturned[x].numPolys*9; i+=3) {
				dataReturned[x].verts[i] += xPos[x];
				dataReturned[x].verts[i+1] += yPos[x];
				dataReturned[x].verts[i+2] += zPos[x];
			}
		}

		// merge + ret
		data.numPolys = numEntries;
		data.verts = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.normals = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.colours = (GLfloat*) malloc(numEntries*12*sizeof(GLfloat));
		GLuint offset = 0;
		for (int x = 0; x < 4; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*9; i++) {
				data.verts[i + offset] = dataReturned[x].verts[i];
				data.normals[i + offset] = dataReturned[x].normals[i];

			}
			offset += dataReturned[x].numPolys*9;
		}
		offset = 0;
		for (int x = 0; x < 4; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*12; i++) {
				data.colours[i + offset] = dataReturned[x].colours[i];
			}
			offset += dataReturned[x].numPolys*12;
		}

		return data;
	}

	SnowGeneratorData opacityVarianceExperiment() {
		SnowGeneratorData data;
		SnowGeneratorData dataReturned[8];
		GLuint numEntries = 0;
		GLfloat xPos[8], yPos[8], zPos[8];

		SnowGenerator snowGeneratorWet = SnowGenerator(WET_SNOW_TEMP);
		// modded wet snow
		dataReturned[0] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, EPS_OPACITY_MOESLUND, NUM_LAYERS_WET_MOESLUND);
		xPos[0] = -10, yPos[0] = 3, zPos[0] = 0;

		// modded wet snow w/ +- 10% variance
		dataReturned[1] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, 0.1, NUM_LAYERS_WET_MOESLUND);
		xPos[1] = -3, yPos[1] = 3, zPos[1] = 0;

		// modded wet snow w +- 25% variance
		dataReturned[2] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, 0.25, NUM_LAYERS_WET_MOESLUND);
		xPos[2] = 3, yPos[2] = 3, zPos[2] = 0;

		// modded wet snow w +- 50% variance
		dataReturned[3] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, 0.5, NUM_LAYERS_WET_MOESLUND);
		xPos[3] = 10, yPos[3] = 3, zPos[3] = 0;

		SnowGenerator snowGeneratorDry = SnowGenerator(DRY_SNOW_TEMP);
		// modded dry snow
		dataReturned[4] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, EPS_OPACITY_MOESLUND, NUM_LAYERS_DRY_MOESLUND);
		xPos[4] = -4, yPos[4] = -3, zPos[4] = 0;

		// modded dry snow w/ +- 10% variance
		dataReturned[5] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, 0.1, NUM_LAYERS_DRY_MOESLUND);
		xPos[5] = -2, yPos[5] = -3, zPos[5] = 0;

		// modded dry snow w/ +- 25% variance
		dataReturned[6] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, 0.25, NUM_LAYERS_DRY_MOESLUND);
		xPos[6] = 2, yPos[6] = -3, zPos[6] = 0;

		// modded dry snow w/ +- 50% variance
		dataReturned[7] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, 0.5, NUM_LAYERS_DRY_MOESLUND);
		xPos[7] = 4, yPos[7] = -3, zPos[7] = 0;

		// update pos
		for (int x = 0; x < 8; x++) {
			numEntries += dataReturned[x].numPolys;
			for (int i = 0; i < dataReturned[x].numPolys*9; i+=3) {
				dataReturned[x].verts[i] += xPos[x];
				dataReturned[x].verts[i+1] += yPos[x];
				dataReturned[x].verts[i+2] += zPos[x];
			}
		}

		// merge + ret
		data.numPolys = numEntries;
		data.verts = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.normals = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.colours = (GLfloat*) malloc(numEntries*12*sizeof(GLfloat));
		GLuint offset = 0;
		for (int x = 0; x < 8; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*9; i++) {
				data.verts[i + offset] = dataReturned[x].verts[i];
				data.normals[i + offset] = dataReturned[x].normals[i];

			}
			offset += dataReturned[x].numPolys*9;
		}
		offset = 0;
		for (int x = 0; x < 8; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*12; i++) {
				data.colours[i + offset] = dataReturned[x].colours[i];
			}
			offset += dataReturned[x].numPolys*12;
		}

		return data;
	}

	/**
	 * Experiment for determining the optimal number of laters for wet and dry snow.
	 * @return Data to render.
	 */
	SnowGeneratorData numLayersExperiment() {
		SnowGeneratorData data;
		SnowGeneratorData dataReturned[8];
		GLuint numEntries = 0;
		GLfloat xPos[8], yPos[8], zPos[8];

		// moeslund wet snow
		dataReturned[0] = getMoeslundWet();
		xPos[0] = -10, yPos[0] = 3, zPos[0] = 0;

		// moeslund dry snow
		dataReturned[1] = getMoeslundDry();
		xPos[1] = -3, yPos[1] = 3, zPos[1] = 0;

		SnowGenerator snowGeneratorWet = SnowGenerator(WET_SNOW_TEMP);
		SnowGenerator snowGeneratorDry = SnowGenerator(DRY_SNOW_TEMP);
		// wet snow w/ 4 layers
		dataReturned[2] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, EPS_OPACITY, 4);
		xPos[2] = 3, yPos[2] = 3, zPos[2] = 0;

		// dry snow w/ 6 layers
		dataReturned[3] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, EPS_OPACITY, 6);
		xPos[3] = 10, yPos[3] = 3, zPos[3] = 0;

		// wet snow w/ 5 layers
		dataReturned[4] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, EPS_OPACITY, 5);
		xPos[4] = -10, yPos[4] = -3, zPos[4] = 0;

		// dry snow w/ 6 layers
		dataReturned[5] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, EPS_OPACITY, 6);
		xPos[5] = -3, yPos[5] = -3, zPos[5] = 0;

		// wet snow w/ 5 layers
		dataReturned[6] = snowGeneratorWet.generateSnowOnceExperimental(EPS_THETA_WET, EPS_PHI_WET, OPACITY_COEFF, EPS_OPACITY, 5);
		xPos[6] = 3, yPos[6] = -3, zPos[6] = 0;

		// dry snow w/ 7 layers
		dataReturned[7] = snowGeneratorDry.generateSnowOnceExperimental(EPS_THETA_DRY, EPS_PHI_DRY, OPACITY_COEFF, EPS_OPACITY, 7);
		xPos[7] = 10, yPos[7] = -3, zPos[7] = 0;

		// update pos
		for (int x = 0; x < 8; x++) {
			numEntries += dataReturned[x].numPolys;
			for (int i = 0; i < dataReturned[x].numPolys*9; i+=3) {
				dataReturned[x].verts[i] += xPos[x];
				dataReturned[x].verts[i+1] += yPos[x];
				dataReturned[x].verts[i+2] += zPos[x];
			}
		}

		// merge + ret
		data.numPolys = numEntries;
		data.verts = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.normals = (GLfloat*) malloc(numEntries*9*sizeof(GLfloat));
		data.colours = (GLfloat*) malloc(numEntries*12*sizeof(GLfloat));
		GLuint offset = 0;
		for (int x = 0; x < 8; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*9; i++) {
				data.verts[i + offset] = dataReturned[x].verts[i];
				data.normals[i + offset] = dataReturned[x].normals[i];

			}
			offset += dataReturned[x].numPolys*9;
		}
		offset = 0;
		for (int x = 0; x < 8; x++) {
			for (int i = 0; i < dataReturned[x].numPolys*12; i++) {
				data.colours[i + offset] = dataReturned[x].colours[i];
			}
			offset += dataReturned[x].numPolys*12;
		}

		return data;
	}

public:
	/**
	 * Constructor for SnowGeneratorExperimentation.
	 * @param numParticles - Number of snow particles to generate.
	 * @param extentInp - Extent of volume in which to generate the particles, where extentInp[0] is a pair for the x extent,
	 * extentInp[1] is a pair for the y extent, and extentInp[2] is a pair for the z extent. If numParticles = 1 this
	 * parameter has no effect and the snow particle is generated at the origin.
	 * @param temp - Temperature of the simulation.
	 * @param whichAlg - Which algorithm to use for the snow particle generation. Either the Moeslund algorithm (1) or the
	 * experimental algorithm (2). Constants for these are defined in SnowConstants.hpp (MOESLUND_ALG and EXPERIMENTAL_ALG, respectively).
	 */
	SnowGeneratorExperimentation(GLuint whichExp) : whichExp(whichExp) {
		// load shaders
		programID = LoadShaders( "shaders/PhongVertexShader.vertexshader", "shaders/PhongFragmentShader.fragmentshader");
		MVPID = glGetUniformLocation(programID, "MVP");
		MID = glGetUniformLocation(programID, "M");
		VID = glGetUniformLocation(programID, "V");
		LightPosID = glGetUniformLocation(programID, "LightPosition_worldspace");
		alphaID = glGetUniformLocation(programID, "alpha");
		glUseProgram(programID);

		setupVAO();
	}

	/**
	 * Default constructor for SnowGeneratorExperimentation.
	 */
	SnowGeneratorExperimentation() : SnowGeneratorExperimentation(NUM_LAYERS_EXP + 1) {};

	/**
	 * Setup VAOs.
	 */
	void setupVAO() {
		glGenVertexArrays(1, &vertexArrayID);
		glBindVertexArray(vertexArrayID);

		// gen snow
		if (whichExp == DEG_OF_ALLOWANCE_EXP) {
			data = degOfAllowanceExperiment();
		} else if (whichExp == OPACITY_EXP) {
			data = opacityExperiment();
		} else if (whichExp == OPACITY_VARIANCE_EXP) {
			data = opacityVarianceExperiment();
		} else if (whichExp == NUM_LAYERS_EXP) {
			data = numLayersExperiment();
		} else {
			SnowGenerator snowGenerator = SnowGenerator();
			data = snowGenerator.generateSnowOnceExperimental();
		}

		// vertices
		glGenBuffers(1, &vertBuffer);
		glBindBuffer(GL_ARRAY_BUFFER, vertBuffer);
		glBufferData(GL_ARRAY_BUFFER, sizeof(GLfloat) * data.numPolys * 9, data.verts, GL_STATIC_DRAW);
		glEnableVertexAttribArray(0);
		glVertexAttribPointer(
			0,                                // attribute. No particular reason for 1, but must match the layout in the shader.
			3,                                // size
			GL_FLOAT,                         // type
			GL_FALSE,                         // normalized?
			0,                                // stride
			(void*) 0                        // array buffer offset
		);

		// normals
		glGenBuffers(1, &normalBuffer);
		glBindBuffer(GL_ARRAY_BUFFER, normalBuffer);
		glBufferData(GL_ARRAY_BUFFER, sizeof(GLfloat) * data.numPolys * 9, data.normals, GL_STATIC_DRAW);
		glEnableVertexAttribArray(1);
		glVertexAttribPointer(
			1,                                // attribute. No particular reason for 1, but must match the layout in the shader.
			3,                                // size
			GL_FLOAT,                         // type
			GL_TRUE,                         // normalized?
			0,                                // stride
			(void*) 0                        // array buffer offset
		);

		// colours
		glGenBuffers(1, &colorBuffer);
		glBindBuffer(GL_ARRAY_BUFFER, colorBuffer);
		glBufferData(GL_ARRAY_BUFFER, sizeof(GLfloat) * data.numPolys * 12, data.colours, GL_STATIC_DRAW);
		glEnableVertexAttribArray(2);
		glVertexAttribPointer(
			2,                                // attribute. No particular reason for 1, but must match the layout in the shader.
			4,                                // size
			GL_FLOAT,                         // type
			GL_FALSE,                         // normalized?
			0,                                // stride
			(void*) 0                        // array buffer offset
		);

		glBindBuffer(GL_ARRAY_BUFFER, 0);
		glBindVertexArray(0);
	}

	/**
	 * Draw function.
	 * @param lightPos - Position of the light source.
	 * @param M - Model (transformation) matrix.
	 * @param V - View matrix.
	 * @param P - Projection matrix.
	 */
	void draw(glm::vec3 lightPos, glm::mat4 M, glm::mat4 V, glm::mat4 P) {
		glm::mat4 MVP = P*V*M;
		glBindVertexArray(vertexArrayID);
		glUseProgram(programID);

		glUniformMatrix4fv(MVPID, 1, GL_FALSE, &MVP[0][0]);
		glUniformMatrix4fv(MID, 1, GL_FALSE, &M[0][0]);
		glUniformMatrix4fv(VID, 1, GL_FALSE, &V[0][0]);
		glUniform3f(LightPosID, lightPos.x, lightPos.y, lightPos.z);
		glUniform1f(alphaID, SHININESS_COEFF);

		glPointSize(3.0f);
		glDrawArrays(GL_TRIANGLES, 0, data.numPolys*3);
		glPointSize(1.0f);

		glUseProgram(0);
		glBindVertexArray(0);
	}
};

#endif
